### ISSUE TITLE
Manage dots on any image a Donkeytail field is added to.

### ISSUE THREAD

**Issue by carlcs** [simplygoodwork/donkeytail-plugin#2]
I think it would be nice if it was possible to not only manage dots on images preconfigured in the field settings but also for images where Donkeytail is added to the asset source. Double click any asset and add dots to it!

**Comment by garrettwinder** [comment]
Hi @carlcs, thanks for reaching out and for the recommendation.

We have a few things in the works for Donkeytail Pro. One of which is the ability to manage assets (canvases) at the entry level rather than the field level, which is a different approach to the use case you've mentioned here, but similar.

I'm going to keep this open so it doesn't get lost. Thanks again. 👍
