### ISSUE TITLE
Dots position incorrect for responsive design

### ISSUE THREAD

**Issue by keyurkadam** [simplygoodwork/donkeytail-plugin#39]
There are 8-10 dots in one image and all except two are correct across all devices. Is there anyone who can provide me with a solution to this problem?

screenshots:
1. https://prnt.sc/HP77l9sjm8Ms
2. https://prnt.sc/CWRnrfLRJMk_
3. https://prnt.sc/m79RXRLXP5Pg

Donkeytail version: 2.0.6
craft cms: 3.7.46

Code: https://prnt.sc/9k-90W-qe6aE

**Comment by chrisrowe** [comment]
Hey!

Do you have this online any where for us to try and debug with you? If it's only affecting a couple of pins there's likely some other CSS at play here, maybe your `pointer-wrp` class? 

You could also remove and re-add those pins, or add some others and see if you spot a pattern?

**Comment by keyurkadam** [comment]
Hello,

yes i have this online. https://www.orthoticmotion.com.au/
https://prnt.sc/_57GdS-SIbfk

**Comment by chrisrowe** [comment]
Hey!

It looks like the dots are in the correct place (25% left) but your background is being stretched. Removing `object-fit: cover` on the image resolves it.

![](http://up.chri.sr/Screen-Shot-2022-10-10-10-43-50.48-1665395033.png)

Since this is all front end related and nothing to do with Donkeytail I'm going to close this one out.
