### ISSUE TITLE
What is Auto-Select Canvas setting?

### ISSUE THREAD

**Issue by mediagirl** [simplygoodwork/donkeytail-plugin#41]
Can you clarify what this setting does/means? It's on the settings page when creating/editing the Donkeytail field.

**Auto-Select Canvas**
Whether the canvas is auto-selected when editing an image asset

**Comment by andrewmenich** [comment]
Hi @mediagirl, that's a great question. This option is for when you want to add a Donkeytail field to an Asset rather than an Entry or Category. When enabled, a Donkeytail field added to an Asset element will use said Asset as the canvas for the Donkeytail field. Here's a screenshot to clarify: 
![SCR-20230203-l2i](https://user-images.githubusercontent.com/29585821/216701320-eb7eac1f-8244-4c02-9672-b6bbf68ed7ae.jpeg)

We'll update the field text to be more descriptive in the next update!
